# And see https://gohugo.io/getting-started/configuration/
baseURL = "/"
title = "Shuey猫舍"
enableRobotsTXT = true
enableEmoji = true
theme = "kagome"
copyright = "© 2017-2024 Shuey Yuen"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 9              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
walineComment = "walineComment"      # disqus_shortname
googleAnalytics = "UA-132577144-1"      # UA-XXXXXXXX-X

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use

[author]
  name = "Shuey Yuen"
  email = "cofalconer@petalmail.com"
  description = "百工之人，不恥相師"
  avatar = "/images/avatar.png"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "文章"
    weight = 10
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "标签"
    weight = 30
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "分类"
    weight = 40
    identifier = "categories"
    url = "/categories/"
  [[menu.main]]
    name = "项目"
    weight = 40
    identifier = "projects"
    url = "/projects/"

  # 底部社交图标
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/ShueyYuen"
    weight = 1
  [[menu.social]]
    identifier = "email"
    name = "email"
    url = "mailto:cofalconer@petalmail.com"
    weight = 2
  [[menu.social]]
    identifier = "bilibili"
    name = "bilibili"
    url = "https://space.bilibili.com/44685985"
    weight = 3
  [[menu.social]]
    identifier = "zhihu"
    name = "zhihu"
    url = "https://zhihu.com/people/shueyyuen"
    weight = 4
  [[menu.social]]
    identifier = "csdn"
    name = "CSDN"
    url = "https://blog.csdn.net/weixin_42345325"
    weight = 5

[params]
  since = "2017"            # Site creation time          # 站点建立时间
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  keywords = ["shuey yuen", "simulator","javascript", "前端"]
  description = "Blog of Shuey Yuen, to share my idea."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"
  toc = true                # 是否开启目录

  # 国内备案号
  beian = "皖ICP备2023022130号-1"
  # TOC目录出现字符长度限制
  toc_show_len = 300

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # clarityID = "b43ixctzrv"    # bing的热力图

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true


  [params.widget]
    # 相关文章推荐数量
    articles_count = 4
    # 分类相关显示数量
    categories_count = 2
    # 标签相关显示数量
    tags_count = 6

  [params.CDN]
    enable = true
    host = "https://cdn.shuey.fun"


  [params.algolia]
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params = ["categories", "tags"]
    appId = "YQOQ4NTHKU"
    indexName = "post"
    searchOnlyKey = "d8edf6d7734befcee737833602d146d5"

[markup]
  defaultMarkdownHandler = "goldmark"  # blackfriday or goldmark
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[outputs]
  home = ['HTML', 'RSS', 'Algolia']
  page = ['HTML']

[outputFormats]
  [outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[Blackfriday]
  hrefTargetBlank = true

[build]
  noJSConfigInAssets = true
